server:
  servlet:
    context-path: /picloud
    session:
      cookie:
        same-site: None
        secure: true
spring:
  application:
    name: picture
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_DATABASE_URL}
#  profiles:
#    active: local
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # Logging is on for dev env only
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

aws:
  s3:
    client:
      region: ${AWS_BUCKET_REGION}
      bucket: ${AWS_BUCKET_NAME}
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}