server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: picture
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture
    username: root
    password: wuweiyang
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      connect-timeout: 5000
#  profiles:
#    active: local
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # Logging is on for dev env only
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# springdoc-openapi project configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: holt.picture.controller
knife4j:
  enable: true
  setting:
    language: en


aws:
  s3:
    client:
      region: xxxx
      bucket: xxxx
      access-key: xxxx
      secret-key: xxxx